version: '3.4'

services:
  mongo:
    image: mongo:5.0.6
    restart: always
    volumes:
      - "data_db:/data/db"

  mongo-express:
    image: mongo-express:0.54
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  redis:
    image: redis:6.0.7
    restart: always

  mirror:
    tty: true
    build:
      context: .
    command: python3 mirror.py
    restart: always
    env_file:
      - ".env"

volumes:
  data_db:
    external: true