version: '3.1'

services:
  redis:
    image: redis:6.0.7
    container_name: redis
    #restart: always

  mirror:
    tty: true
    build:
      context: .
    command: python3 mirror.py
    #restart: always
    env_file:
      - ".env"
